# Header

menu:
  主页: /
  归档: /archives/index.html
  分类: /categories
  动态: /dynamic
  导航: /tools/

# SubNav
subnav:
  github: "https://github.com/liuliange"
  weibo: "https://weibo.com/u/1796705035"
  qq: "https://qm.qq.com/cgi-bin/qm/qr?k=rZLHYMMvE_Ddv6vORxpef78d_X3UleO8"
  # weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:you@example.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

# 右上角丝带角标（Corner Badge）
# enable: false 可关闭；text 为角标文字；url 为点击跳转
corner_badge:
  enable: true
  text: '微信：525821377'
  url: 'https://my.feishu.cn/wiki/RMKjwYflBiru4qkyktjcHl7mnLh?from=from_copylink'

# 你的名字跟网站副标题
author: 榴莲哥
subtitle: '臭味相投我们是朋友'

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: '/assets/img/alipay.jpg'
# 微信二维码图片地址
weixin: '/assets/img/WeChatPay.jpg'

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/img/logo.jpg

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  缤果网: https://binguo.net
  特价团: https://tejiatuan.cn/
  特惠团: https://tehuituan.cn/
  特卖团: https://temaituan.cn/
  捡便宜: https://jianpianyi.cn/
  资源库: https://199909.com
  资源搜索: https://pan.binguo.net

aboutme: 榴莲哥<br/><br/>来自广西崇左<br/>热爱生活喜欢折腾 目前是一枚水果搬运工<br/>胆小认生不易相处 年轻无为卖果为生<br/>日常琐碎不堪记忆无处安放 遂筑博客一枚以作日记之用

# 是否开启字数统计
# 不需要使用，直接设置值为false，或注释掉
word_count: True

# 是否开启访问量统计功能(不蒜子)
busuanzi:
  enable: true

# 版权声明
#在需要进行版权声明的文章的md文件头部，设置属性declare: true。
#版权基础设定：0-关闭声明； 1-文章对应的md文件里有declare: true属性，才有版权声明； 2-所有文章均有版权声明
declare:
  declare_type: 1
  licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/        #当前应用的版权协议地址。
  licensee_name: 'CC BY-NC-SA 4.0'                                        #版权协议的名称
  licensee_alias: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'       # alias别名
  licensee_img: https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png    #版权协议的Logo

#文章结束
essayending_type: 1 #0关闭文章结束提示 2全开 1需要在文章开头加上 
essayending: true

# Pangu.js | 中英文字间距美化
pangu: true

# Tab Title Change | 标签页标题切换
tab_title_change: 
  enable: true
  left_tab_title: '(つェ⊂) 我藏好了哦~ '
  return_tab_title: '(*´∇｀*) 被你发现啦~ '